### ISSUE TITLE
Crashing on creating a new panel 

### ISSUE THREAD

**Issue by carlosdelaomartinez** [eamrhein/Offshoot#63]
![Screen Shot 2019-10-17 at 9 54 55 PM](https://user-images.githubusercontent.com/31365811/67066823-fd2bc200-f128-11e9-9249-e09172ad7bfa.png)

**Comment by eamrhein** [comment]
what are the steps to reproduce?

**Comment by eamrhein** [comment]
So, I can't figure out what is causing this. Problems I see:

1.  there seems to be a problem with our router where the word login is put in behind the hash.

2.  Panels get cleared inside of the create panel form. Then the like button requires panel in order to render. 

In this mapSTP panels is empty when coming from the createpanel route.
```` 
const mapStateToProps = (state, ownProps) => ({
    panel: state.entities.panels[ownProps.match.params.panelId],
    currentUser: state.session.user
})

````
